import React from 'react';
import type { Metadata } from 'next';
import 'normalize.css/normalize.css';
import './globals.css';
import StyledComponentsRegistry from '@/components/registry';
import { Jura } from 'next/font/google';
import MainLayout from './components/main-layout';

const inter = Jura({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body className={inter.className}>
          <MainLayout>{children}</MainLayout>
        </body>
      </StyledComponentsRegistry>
    </html>
  );
}
